[package]
name = "mobius"
version = "0.1.0"
authors = ["Dante Helmore <frostu8@protonmail.com>"]
edition = "2021"

description = "An asset packager for Doom PK3s"

[dependencies]
floem = "0.2"
im = "15"
walkdir = "2"
